name: Upload Python Package

on:
  push:
    branches:
      - main  # or the name of your default branch

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check commit message
      id: check_message
      run: |
        echo "::set-output name=message::$(git log -1 --pretty=format:"%s")"
    - name: Set up Python
      if: contains(steps.check_message.outputs.message, 'publish')
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      if: contains(steps.check_message.outputs.message, 'publish')
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      if: contains(steps.check_message.outputs.message, 'publish')
      run: python -m build
    - name: Publish package
      if: contains(steps.check_message.outputs.message, 'publish')
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
